export default {
    //Checklist
    SET_CHECKLIST: "SET_CHECKLIST",
    FETCH_CHECKLIST: "FETCH_CHECKLIST",

    //Platforms
    SET_PLATFORMS: "SET_PLATFORMS",
    FETCH_PLATFORMS: "FETCH_PLATFORMS"
};
